name: Build app

on: workflow_dispatch

jobs:    
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Build app
              run: |
                go build -buildvcs=false
                go install fyne.io/fyne/v2/cmd/fyne@latest
                export PATH=${PATH}:`go env GOPATH`/bin
                mkdir -p output/dmg
                fyne package -os darwin
                hdiutil create -format UDZO -srcfolder "ProcessMonitor.app" "ProcessMonitor.dmg"
                mv "ProcessMonitor.dmg" output/dmg/

            - name: Publish dmg
              uses: actions/upload-artifact@v3
              with:
                name: "dmg"
                path: "output/dmg"